import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/Componets/Header";
import SessionProviders from "@/context/SessionProviders";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const Poppin = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home - NextAuth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionProviders>
      <html lang="en">
        <body className={`${Poppin.className}`}>
          <Header />
          {children}
        </body>
      </html>
    </SessionProviders>
  );
}
